[project]
name = "flask-app"
version = "0.1.0"
description = "Une app Flask déployée sur Render"
dependencies = [
    "flask",
    "gunicorn"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
